In [3]:
import numpy as np
import matplotlib.pyplot as plt
import torch

现在以该图片展示的神经网络模型做前馈处理进行运行操作展示

<img src="https://img2024.cnblogs.com/blog/3693258/202511/3693258-20251124095012592-885343576.png" alt="image-20251124095010213" style="zoom:33%;" />

In [4]:
def forward(x1 , x2):
    """定义前馈函数
    Arges:
        @ x1,x2:自变量
    Returns:
        @ res 输出矩阵
    """
    W = np.array([[1 , 3 , 5] , [2 , 4 , 6]])
    X = np.array([x1 , x2])
    res = np.dot(X , W)
    return res 
forward(2 , 3)

array([ 8, 18, 28])

In [ ]:
def forward_three(x1 , x2):
    """定义双层前馈函数
    Args:
        @ x1,x2:自变量
    Returns:
        @ Y :输入矩阵
    """
    a1, a2, a3 , a4 ,a5 ,a6 = 1,2,3,4,5,6
    W1 = np.array([[a1 , a3 , a5],[a2 , a4 , a6]])
    b1 , b2 , b3 , b4 , b5 , b6 = 1,2,3,4,5,6
    W2 = np.array([[b1 , b2],[b3 , b4],[b5 , b6]])
    X = np.array([x1 , x2])
    Y = np.dot(np.dot(X , W1) , W2)
    return Y
forward_three(1 , 3)

array([167, 212])

上面全部均是再不加偏置项和激活函数的前提之下进行使用的，但是一旦加上了偏置项和激活函数整一个神经网络的前馈处理就变得比较的复杂和难弄

在加上了偏置项的前提下重新来书写一下双层和三层的神经网络

In [5]:
def Forward_two(x1 , x2):
    """定义拥有偏置项的双层神经网络前馈函数
    Args:
        @ x1,x2:自变量
    Returns:
        @ res :输出矩阵
    """
    w11 , w12 , w21 , w22 , w31 , w32 , b1 , b2 , b3  =1, 2 , 3 , 4 , 5 , 6 , 7 , 8,  9
    W_B_1 = np.array([[w11 , w12 , b1],[w21 , w22 , b2],[w31 , w32 , b3]])
    X = np.array([x1 , x2 , 1])
    res = np.dot(X , W_B_1)
    return res
Forward_two(1 , 2)

array([12, 16, 32])

In [10]:
def Forward_three(x1 , x2):
    """定义拥有偏置项的三层神经网络前馈模型
    Args:
        @ x1 , x2:自变量
    Returns:
        @ res : 输出矩阵
    """
    w11 , w12 , w21 , w22 , w31 , w32 , b1 , b2 , b3  =1, 2 , 3 , 4 , 5 , 6 , 7 , 8,  9
    W_B_1 = np.array([[w11 , w12 , b1],[w21 , w22 , b2],[w31 , w32 , b3]])
    X = np.array([x1 , x2 , 1])
    a1 = np.dot(X , W_B_1)
    w11 , w12 , w21 , w22 , w31 , w32 , b1 , b2 , b3  =1, 2 , 3 , 4 , 5 , 6 , 7 , 8,  9
    W_B_2 = np.array([[w11 , w12 , b1],[w21 , w22 , b2],[w31 , w32 , b3]])
    X = np.array([X[0] , X[1] , 1])
    res = np.dot(X , W_B_2)
    return res
Forward_three(1 , 2)

array([12, 16, 32])

现在给其加上激活函数的使用，激活函数主要有两种，其一为sigmoid函数，其二为ReLu函数


In [13]:
def sigmoid(x):
    """ Sigmoid函数的定义
    Args:
        @x:输入的矩阵（主要是numpy中的矩阵类型)
    Returs:
        @ return: 输出矩阵
    """
    return 1/(1+np.exp(-x))

In [14]:
def ReLU(x):
    """ReLU函数的定义
    Args:
        @x 输入的矩阵
    Returns:
        @return: 输出的矩阵
    """
    return np.maximum(x , 0)

现在将这两个激活函数带入到神经网络的前馈模型中来实现相关的一些操作

In [23]:
# 首先是一个基本的双层神经网络模型的运行、
def FORWARD_TWO(x1 ,x2 ):
    """定义拥有偏置项以及使用了sigomid激活函数的双层神经网络前馈函数
    Args:
        @ x1,x2:自变量
    Returns:
        @ res :输出矩阵
    """
    X = np.array([x1 , x2 , 1])
    w11 , w12 , b1 , w21 , w22 , b2 , w31 , w32 , b3 = 1,  2 , 3 ,  3 , 4,  5 , 5 , 6 , 6 
    W_B = np.array([[w11 , w12 , b1] , [w21 , w22 , b2] , [w31 , w32 , b3]])
    a1 = np.dot(X , W_B)
    res = sigmoid(a1)
    return res 
FORWARD_TWO(1, 0.5)

array([0.99944722, 1.        , 0.99998987])

In [31]:
# 现在来最后总结一个最大的三层神经网络包括了偏置以及激活函数的前馈反应
def init_network():
    """初始化神经网络的前馈模型函数，其中的所有权重和偏置参数均是随意取得
    Args:
        none
    return:
        @ network:一个包括了权重偏置等参数的字典
    """
    network = {}
    network['W1'] = np.array([[0.1 , 0.3 , 0.5],[0.3 , 0.6 , 0.2]])
    network['b1'] = np.array([0.5, 0.4 , 0.8])
    network['W2'] = np.array([[0.5 , 0.6],[0.6 , 0.3],[0.8 , 0.1]])
    network['b2'] = np.array([[0.4 , 0.6]])
    network['W3'] = np.array([[0.4 , 0.8] , [0.4 , 0.2] ])
    network['b3'] = np.array([0.5 , 0.9])
    return network

def forward(network , x):
    """神经网络的初始化前馈模型函数
    Args:
        @ network:字典变量，其中包括了各个初始化的偏置以及权重
        @ x: 自变量矩阵
    Returns:
        @ z1 : 最后输出矩阵
    """
    W1 , W2 , W3 = network['W1'],network['W2'],network['W3']
    b1 , b2 , b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x , W1) + b1 
    z1 = sigmoid(a1)
    a2 = np.dot(z1 , W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2 , W3) + b3
    z3 = sigmoid(a3)
    return z3

network = init_network()
x = np.array([1.0 , 0.5])
y = forward(network , x)
print(y)

[[0.76115683 0.85142908]]
